name: notebook_docs
dependencies:
- python=3.8
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- jupyter_client
- ipykernel
- sphinx
- terminado
- pip:
  - nbsphinx
  - Send2Trash
  - prometheus_client
  - sphinxcontrib_github_alt
